apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: flux-demo
  labels:
    app: test
  name: test
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: flux-demo
  type: NodePort
status:
  loadBalancer: {}
